spring:
  application:
    name: ORDER-SERVICE

server:
  port: 8500
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true