
spring:
  application:
    name: USER-SERVICE
server:
  port: 8521
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true